# Generated by Django 5.1.3 on 2024-11-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_budget_category_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='custom_category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='custom_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
